
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:12 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:12 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/W3
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.9.8+b34f75857 для .NET Framework
      Сборка начата 09.12.2025 13:07:43.
      
      Проект "D:\\DaraProgram\\prog\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\DaraProgram\\prog\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "D:\\DaraProgram\\prog\\CMakeFiles\\3.28.0-rc5\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.84
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/DaraProgram/prog/CMakeFiles/3.28.0-rc5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:12 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/W3;/GR;/EHsc
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.9.8+b34f75857 для .NET Framework
      Сборка начата 09.12.2025 13:07:44.
      
      Проект "D:\\DaraProgram\\prog\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\DaraProgram\\prog\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "D:\\DaraProgram\\prog\\CMakeFiles\\3.28.0-rc5\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:00.84
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/DaraProgram/prog/CMakeFiles/3.28.0-rc5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:12 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-b5ha65"
      binary: "D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-b5ha65"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MSVC_DEBUG_INFORMATION_FORMAT: "$<IF:$<AND:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>,$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>>"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-b5ha65'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_1a57e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.9.8+b34f75857 для .NET Framework
        Сборка начата 09.12.2025 13:07:45.
        
        Проект "D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-b5ha65\\cmTC_1a57e.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_1a57e.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Создание каталога "D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-b5ha65\\Debug\\".
          Создание каталога "cmTC_1a57e.dir\\Debug\\cmTC_1a57e.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_1a57e.dir\\Debug\\cmTC_1a57e.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_1a57e.dir\\Debug\\cmTC_1a57e.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_1a57e.dir\\Debug\\\\" /Fd"cmTC_1a57e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_1a57e.dir\\Debug\\\\" /Fd"cmTC_1a57e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-b5ha65\\Debug\\cmTC_1a57e.exe" /INCREMENTAL /ILK:"cmTC_1a57e.dir\\Debug\\cmTC_1a57e.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-b5ha65/Debug/cmTC_1a57e.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-b5ha65/Debug/cmTC_1a57e.lib" /MACHINE:X64  /machine:x64 cmTC_1a57e.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_1a57e.vcxproj -> D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-b5ha65\\Debug\\cmTC_1a57e.exe
        FinalizeBuildStatus:
          Файл "cmTC_1a57e.dir\\Debug\\cmTC_1a57e.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_1a57e.dir\\Debug\\cmTC_1a57e.tlog\\cmTC_1a57e.lastbuildstate".
        Сборка проекта "D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-b5ha65\\cmTC_1a57e.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.78
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:12 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-y3xero"
      binary: "D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-y3xero"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MSVC_DEBUG_INFORMATION_FORMAT: "$<IF:$<AND:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>,$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>>"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-y3xero'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_ef8d3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.9.8+b34f75857 для .NET Framework
        Сборка начата 09.12.2025 13:07:46.
        
        Проект "D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-y3xero\\cmTC_ef8d3.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_ef8d3.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Создание каталога "D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-y3xero\\Debug\\".
          Создание каталога "cmTC_ef8d3.dir\\Debug\\cmTC_ef8d3.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_ef8d3.dir\\Debug\\cmTC_ef8d3.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_ef8d3.dir\\Debug\\cmTC_ef8d3.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ef8d3.dir\\Debug\\\\" /Fd"cmTC_ef8d3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_ef8d3.dir\\Debug\\\\" /Fd"cmTC_ef8d3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-y3xero\\Debug\\cmTC_ef8d3.exe" /INCREMENTAL /ILK:"cmTC_ef8d3.dir\\Debug\\cmTC_ef8d3.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-y3xero/Debug/cmTC_ef8d3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/DaraProgram/prog/CMakeFiles/CMakeScratch/TryCompile-y3xero/Debug/cmTC_ef8d3.lib" /MACHINE:X64  /machine:x64 cmTC_ef8d3.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_ef8d3.vcxproj -> D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-y3xero\\Debug\\cmTC_ef8d3.exe
        FinalizeBuildStatus:
          Файл "cmTC_ef8d3.dir\\Debug\\cmTC_ef8d3.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_ef8d3.dir\\Debug\\cmTC_ef8d3.tlog\\cmTC_ef8d3.lastbuildstate".
        Сборка проекта "D:\\DaraProgram\\prog\\CMakeFiles\\CMakeScratch\\TryCompile-y3xero\\cmTC_ef8d3.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.81
        
      exitCode: 0
...
